### ISSUE TITLE
Vendors selling unlimited green items

### ISSUE THREAD

**Issue by Mango-Ray** [xgdglb9fpg1j/grizztracker#10]
NPCs that sell uncommon items that should be limited.

npc=1214/aldren-cordon
npc=1454/jennabink-powerseam
npc=1459/naela-trance
npc=1441/brak-durnad
npc=2805/deneb-walker
npc=1307/charys-yserian
npc=3537/zixil

NPCs that sell non-uncommon items that should be limited (such as potions/herbs/materials)

npc=8305/kixxle
npc=2380/nandar-branson
npc=2812/drovnar-strongbrew

will add more as i come across them

**Comment by xgdglb9fpg1j** [comment]
Implemented (what should be) a global fix for this. Open a new issue if you notice any discrepancies.
