### ISSUE TITLE
Quest : Pool of Tears (low priority)

### ISSUE THREAD

**Issue by Mango-Ray** [xgdglb9fpg1j/grizztracker#23]
quest=1424

Quest has you go around the waters of sunken temple for Atal'ai Artifact (object=30854) to obtain Atal'ai Artifact (item=6175).

Currently, there are only two spawning objects that have a very long respawn timer. you need 10.

**Comment by rach0930** [comment]
There are 15 spawning objects in both the shallow and deep parts of the lake surrounding the temple. They're just difficult to see. Respawn time is 10 minutes.
