### ISSUE TITLE
Quest -  Azurmyst Isle - Inoculation - Innoculated Owlkin don't despawn.

### ISSUE THREAD

**Issue by ameliandra** [xgdglb9fpg1j/grizztracker#29]
After using the Inoculating Crystal on Nestlewood Owlkin, a new model appears, Inoculated Nestlewood Owlkin. This new model takes a very long time to despawn. Longer than it take for a new Nestlewood Owlkin to spawn.

**Comment by xgdglb9fpg1j** [comment]
Couldn't find any data on what the correct despawn timer for Inoculated Nestlewood Owlkin should be, but it was set to 3m (same as the respawn timer for normal Nestlewood Owlkins). Reduced it to 1m. Fix live next restart.

**Comment by xgdglb9fpg1j** [comment]
Corpses don't cleanly despawn and it's awful.

**Comment by xgdglb9fpg1j** [comment]
Copious amounts of duct tape and derogatory language applied. Fixed.
