### ISSUE TITLE
Mob - Bloodmyst Isle - Webbed Creature - Several issues with the cocoon.

### ISSUE THREAD

**Issue by ameliandra** [xgdglb9fpg1j/grizztracker#36]
1. The cocoon moves around when it should be stationary.
2. When breaking the cocoon, the wrong mobs can spawn from them such as named quest mobs such as Deathclaw and Lord Xiz and other spiders.

**Comment by rach0930** [comment]
Cocoons are supposed to be able to spawn named quest mobs along with the spiders (provide proof that it is incorrect).

**Comment by xgdglb9fpg1j** [comment]
Movement fixed. Live after next restart.
