### ISSUE TITLE
Mob - Bloodmyst Isle - Totems - There are several Strength of Earth totem scattered on Bloodmyst Isle

### ISSUE THREAD

**Issue by ameliandra** [xgdglb9fpg1j/grizztracker#39]
All around Bloodmyst Isle, level 20 Strength of Earth totems can be found.

![totem](https://cloud.githubusercontent.com/assets/13498094/8890273/b35e0cb4-32c8-11e5-8136-e44ce3464356.jpg)

**Comment by xgdglb9fpg1j** [comment]
Fix live next restart.
