### ISSUE TITLE
Mob - Ashenvale - Foulweald Den Watcher - They hit hundreds of times in a single animation.

### ISSUE THREAD

**Issue by ameliandra** [xgdglb9fpg1j/grizztracker#43]
The Foulweald Den Watcher basically one-shot anything. If you look at combat log after they hit you, you'll notice that they hit you with basically enough attacks to kill you regardless of your hp.

![dmg](https://cloud.githubusercontent.com/assets/13498094/8890861/b95e04fa-32de-11e5-830d-8d440f17c229.png)

**Comment by xgdglb9fpg1j** [comment]
Issue is http://db.vanillagaming.org/?spell=3391 being cast infinitely with no cooldown. Unsure/don't know how to fix at this time. Bandaid fixed by removing the spell from the mob.
