### ISSUE TITLE
Quest - Barrens [Verog the Dervish]

### ISSUE THREAD

**Issue by parkerbrody** [xgdglb9fpg1j/grizztracker#45]
Verog didn't summon after about 50 centaur kills, centaurs didn't say their RP "I am slain, summon Verog!" I'm not sure how many kills it should take but it didn't seem to be working at all.

**Comment by keyliskeyl** [comment]
Possible bandaid fix to just spawn the mob on a 2-3 min respawn in his respective place?

**Comment by xgdglb9fpg1j** [comment]
Bandaid fixed with a 5m spawn timer as per Keyl's suggestion.
