### ISSUE TITLE
Quest - Un'Goro Crater [The Fate of Lar'kowri]

### ISSUE THREAD

**Issue by parkerbrody** [xgdglb9fpg1j/grizztracker#55]
Giant Threshadon Carcass is bugged, can't loot it. Had GM give me the quest item and the rest of the chain works.

**Comment by xgdglb9fpg1j** [comment]
After eight hours of database tinkering and gameobject repositioning, this quest item is now able to be looted, providing you stand in the proper spot relative to the center of the model! Hail Satan!
