### ISSUE TITLE
Quest - Hellfire Peninsula [I Work... For the Horde!]

### ISSUE THREAD

**Issue by parkerbrody** [xgdglb9fpg1j/grizztracker#60]
Can't pick up wood or metal scraps, they shine like they want to be looted but there is no cog and clicking them does nothing. Would assume this doesn't work for the Alliance counterpart either.

**Comment by rach0930** [comment]
This quest works fine for me on both horde and alliance. I suggest trying to clear your cache.

**Comment by illroy** [comment]
I deleted WDB and dropped the quest and picked it up again, still no luck. Maybe we can try it when both of us are online.

**Comment by parkerbrody** [comment]
Oh, it looks like there's some areas with working scrap metal/wood and other areas where it doesn't work. Good enough as-is!
