### ISSUE TITLE
NPC - Black Broodling

### ISSUE THREAD

**Issue by Mango-Ray** [xgdglb9fpg1j/grizztracker#63]
npc=7047

Casts fireballs nonstop. The fireballs hit for 250-310 damage and make killing them at expected level more challenging than necessary.

Lowering the damage to about 170-210 would probably be fine, as other caster mobs in the area hit that hard.

**Comment by xgdglb9fpg1j** [comment]
http://www.wowhead.com/npc=7047/black-broodling#comments:id=382880

Those mobs have always been a pain to deal with and even with the bug here where they like to cast through CC, I'm killing them just fine naked. I'm fairly certain said bug is the main issue and not the actual mobs.
