### ISSUE TITLE
Quest - Hellfire Peninsula "Fel Spirits"

### ISSUE THREAD

**Issue by keyliskeyl** [xgdglb9fpg1j/grizztracker#79]
Using the item "Anchorite Relic" does not spawn spirits, which are supposed to spawn. I'll look for the mob ID for the ones that are supposed to spawn. Should spawn 1 every 20 seconds or so for you to kill.

**Comment by rach0930** [comment]
Put relic down near mobs in the area, wait for blue beam to hit them, kill them, and the spirits will spawn.
