### ISSUE TITLE
Item - Lockboxes

### ISSUE THREAD

**Issue by Mango-Ray** [xgdglb9fpg1j/grizztracker#92]
Lockboxes have a graphical text error, as they are not showing that they're locked, and appearing unlocked.
![captureslockbox](https://cloud.githubusercontent.com/assets/13490949/8921291/9fa57cfe-34a1-11e5-912a-cc47ad457298.PNG)

However, they cannot be opened without lock-picking, which is working as intended.

Affected items: 5760, 4633, 4634, 31952, 5758, 4632, 4638, 4637, 4636, 5759

**Comment by rach0930** [comment]
fix live next restart
